#!/bin/bash

# Quick Test Credentials Printer
# Usage: ./test-credentials.sh

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       E-COMMERCE ADMIN PANEL - TEST CREDENTIALS               ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  🌐 Development Server: http://localhost:5174                 ║"
echo "║  📄 Login Page:         http://localhost:5174/login           ║"
echo "║                                                                ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  👨‍💼 ADMIN USER (Full Access)                                     ║"
echo "║  ───────────────────────────────────────────────────────────  ║"
echo "║  Email:    admin@example.com                                  ║"
echo "║  Password: admin123                                           ║"
echo "║  Access:   All pages, all features                            ║"
echo "║                                                                ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  📊 MANAGER USER (Partial Access)                              ║"
echo "║  ───────────────────────────────────────────────────────────  ║"
echo "║  Email:    manager@example.com                                ║"
echo "║  Password: manager123                                         ║"
echo "║  Access:   Dashboard, Users, Products, Orders                ║"
echo "║                                                                ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  👤 STAFF USER (Limited Access)                               ║"
echo "║  ───────────────────────────────────────────────────────────  ║"
echo "║  Email:    staff@example.com                                  ║"
echo "║  Password: staff123                                           ║"
echo "║  Access:   Dashboard, Orders                                  ║"
echo "║                                                                ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  👁️  VIEWER USER (Read-Only Access)                           ║"
echo "║  ───────────────────────────────────────────────────────────  ║"
echo "║  Email:    viewer@example.com                                 ║"
echo "║  Password: viewer123                                          ║"
echo "║  Access:   Dashboard only                                     ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "ℹ️  IMPORTANT NOTES:"
echo "  • All credentials are for TESTING/DEVELOPMENT only"
echo "  • Replace with real authentication before going to production"
echo "  • Tokens expire in 24 hours (mock)"
echo "  • Session data persists in localStorage"
echo "  • Use DevTools (F12) → Application to see stored tokens"
echo ""
echo "🧪 TESTING CHECKLIST:"
echo "  1. Try login with each user account"
echo "  2. Verify role-based page access"
echo "  3. Check sidebar menu filtering by role"
echo "  4. Test logout and session persistence"
echo "  5. Try accessing unauthorized pages (should show 403)"
echo ""
echo "📚 For more information, see LOGIN_CREDENTIALS.md"
echo ""
